services:
  - type: web
    name: todo-backend
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/demo-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
    healthCheckPath: /
    plan: free

  - type: static   # <-- Changed from "static_site" to "static"
    name: todo-frontend
    rootDir: todo-frontend
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://todo-backend.onrender.com
